"""Add account linking support

Revision ID: 053c230e94fe
Revises: 9a9684cf25b4
Create Date: 2025-11-20 17:44:10.415923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053c230e94fe'
down_revision = '9a9684cf25b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_linking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whitelisted_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # Add columns as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stub', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linked_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE users SET is_stub = FALSE WHERE is_stub IS NULL")
    
    # Now make is_stub NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_stub', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linked_at')
        batch_op.drop_column('is_stub')

    op.drop_table('whitelisted_domains')
    op.drop_table('account_linking_requests')
    # ### end Alembic commands ###
