"""remove seller_id and territory_id from call_logs

Revision ID: 1b1cfedf06a9
Revises: 2cd42a273210
Create Date: 2025-11-19 19:00:55.230255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1cfedf06a9'
down_revision = '2cd42a273210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('call_logs_territory_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('call_logs_seller_id_fkey'), type_='foreignkey')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('territory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('territory_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('call_logs_seller_id_fkey'), 'sellers', ['seller_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('call_logs_territory_id_fkey'), 'territories', ['territory_id'], ['id'])

    # ### end Alembic commands ###
