"""Add territory_view_accounts to user preferences

Revision ID: 3620d38a767d
Revises: b9923cccee0c
Create Date: 2025-11-19 15:57:22.923428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3620d38a767d'
down_revision = 'b9923cccee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('territory_view_accounts', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('territory_view_accounts')

    # ### end Alembic commands ###
