"""Add customer_view_grouped preference to user_preferences

Revision ID: 5d5bcd30c00e
Revises: df733afa6b61
Create Date: 2025-11-18 22:25:07.650740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5bcd30c00e'
down_revision = 'df733afa6b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_view_grouped', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('customer_view_grouped')

    # ### end Alembic commands ###
