"""Add nickname field to Customer model

Revision ID: 736b6a049252
Revises: ad3c9094b262
Create Date: 2025-11-19 13:29:23.595231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736b6a049252'
down_revision = 'ad3c9094b262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
