"""add first_run_modal_dismissed and fix show_customers_without_calls default

Revision ID: 7427e1ce0a16
Revises: drop_whitelist
Create Date: 2025-11-24 18:37:49.574916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7427e1ce0a16'
down_revision = 'drop_whitelist'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_run_modal_dismissed', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('first_run_modal_dismissed')

    # ### end Alembic commands ###
