"""add is_admin field to users table

Revision ID: 9a9684cf25b4
Revises: a455416d15a2
Create Date: 2025-11-20 16:44:20.964083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9684cf25b4'
down_revision = 'a455416d15a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add column with default False for existing rows
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    
    # Set user_id=1 as admin
    op.execute("UPDATE users SET is_admin = TRUE WHERE id = 1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
