"""add show_customers_without_calls preference

Revision ID: aa692aff1d35
Revises: f9035c1c9285
Create Date: 2025-11-21 19:02:42.723185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa692aff1d35'
down_revision = 'f9035c1c9285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_customers_without_calls', sa.Boolean(), nullable=False, server_default='false'))
    
    # Remove server_default after adding column
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('show_customers_without_calls', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('show_customers_without_calls')
    # ### end Alembic commands ###
