"""Add PODs, solution engineers, verticals, seller types and aliases

Revision ID: ad3c9094b262
Revises: f170fa9cd3b1
Create Date: 2025-11-19 12:37:34.300825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3c9094b262'
down_revision = 'f170fa9cd3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_engineers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('pod_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers_verticals',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'vertical_id')
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seller_type', sa.String(length=20), nullable=False))

    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pod_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pods', ['pod_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pod_id')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('seller_type')
        batch_op.drop_column('alias')

    op.drop_table('customers_verticals')
    op.drop_table('solution_engineers')
    op.drop_table('verticals')
    op.drop_table('pods')
    # ### end Alembic commands ###
