"""Convert SolutionEngineer to POD relationship to many-to-many

Revision ID: b9923cccee0c
Revises: 736b6a049252
Create Date: 2025-11-19 15:13:19.434146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9923cccee0c'
down_revision = '736b6a049252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_engineers_pods',
    sa.Column('solution_engineer_id', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.ForeignKeyConstraint(['solution_engineer_id'], ['solution_engineers.id'], ),
    sa.PrimaryKeyConstraint('solution_engineer_id', 'pod_id')
    )
    with op.batch_alter_table('solution_engineers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solution_engineers_pod_id_fkey'), type_='foreignkey')
        batch_op.drop_column('pod_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_engineers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pod_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('solution_engineers_pod_id_fkey'), 'pods', ['pod_id'], ['id'])

    op.drop_table('solution_engineers_pods')
    # ### end Alembic commands ###
