"""add colored_sellers preference

Revision ID: bd08ac6c0932
Revises: 1b1cfedf06a9
Create Date: 2025-11-19 20:01:28.682120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd08ac6c0932'
down_revision = '1b1cfedf06a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colored_sellers', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE user_preferences SET colored_sellers = TRUE WHERE colored_sellers IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('colored_sellers', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('colored_sellers')

    # ### end Alembic commands ###
