"""add customer_sort_by to user preferences

Revision ID: d51b403420aa
Revises: bd08ac6c0932
Create Date: 2025-11-20 10:41:17.477788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51b403420aa'
down_revision = 'bd08ac6c0932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_sort_by', sa.String(length=20), nullable=False, server_default='alphabetical'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('customer_sort_by')

    # ### end Alembic commands ###
