"""add support for multiple account types (microsoft and external)

Revision ID: e4669a996d2e
Revises: 270b4866d807
Create Date: 2025-11-20 15:22:29.195883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4669a996d2e'
down_revision = '270b4866d807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_azure_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_azure_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_azure_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['microsoft_azure_id'])
        batch_op.create_unique_constraint(None, ['external_azure_id'])
    
    # Migrate existing azure_id to the appropriate field based on email domain
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET microsoft_azure_id = azure_id 
        WHERE LOWER(email) LIKE '%@microsoft.com'
    """))
    connection.execute(sa.text("""
        UPDATE users 
        SET external_azure_id = azure_id 
        WHERE LOWER(email) NOT LIKE '%@microsoft.com'
    """))
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('azure_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('users_azure_id_key'), ['azure_id'])
        batch_op.drop_column('external_azure_id')
        batch_op.drop_column('microsoft_azure_id')

    # ### end Alembic commands ###
