"""Add topic_sort_by_calls preference

Revision ID: f170fa9cd3b1
Revises: 5d5bcd30c00e
Create Date: 2025-11-18 23:00:06.831250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f170fa9cd3b1'
down_revision = '5d5bcd30c00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_sort_by_calls', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('topic_sort_by_calls')

    # ### end Alembic commands ###
