"""Add tpid and tpid_url to customers

Revision ID: f8128ba331bb
Revises: 7c156b536c6d
Create Date: 2025-11-18 10:15:15.749793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8128ba331bb'
down_revision = '7c156b536c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add tpid column as nullable
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tpid', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('tpid_url', sa.String(length=500), nullable=True))
    
    # Step 2: Update existing rows with a default TPID value (0)
    op.execute('UPDATE customers SET tpid = 0 WHERE tpid IS NULL')
    
    # Step 3: Make tpid NOT NULL
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('tpid', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('tpid_url')
        batch_op.drop_column('tpid')

    # ### end Alembic commands ###
